# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'diseño.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1280, 738)
        MainWindow.setMinimumSize(QtCore.QSize(1280, 720))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(243, 243, 243))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(252, 253, 253))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(243, 243, 243))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(252, 253, 253))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(252, 253, 253))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(252, 253, 253))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        MainWindow.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Roboto")
        MainWindow.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/dron/Imagenes/Dron_LOGO.png.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        palette = QtGui.QPalette()
        self.centralwidget.setPalette(palette)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.menu = QtWidgets.QWidget(self.centralwidget)
        self.menu.setMinimumSize(QtCore.QSize(100, 671))
        self.menu.setMaximumSize(QtCore.QSize(90, 16777215))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(81, 176, 227))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(78, 152, 246))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(65, 126, 205))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(26, 50, 82))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(34, 67, 109))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(81, 176, 227))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(81, 176, 227))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(153, 178, 209))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(52, 101, 164))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.NoRole, brush)
        brush = QtGui.QBrush(QtGui.QColor(52, 101, 164))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(81, 176, 227))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(78, 152, 246))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(65, 126, 205))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(26, 50, 82))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(34, 67, 109))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(81, 176, 227))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(81, 176, 227))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(153, 178, 209))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(52, 101, 164))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.NoRole, brush)
        brush = QtGui.QBrush(QtGui.QColor(52, 101, 164))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(26, 50, 82))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(81, 176, 227))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(78, 152, 246))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(65, 126, 205))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(26, 50, 82))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(34, 67, 109))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(26, 50, 82))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(26, 50, 82))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(81, 176, 227))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(81, 176, 227))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(52, 101, 164))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(52, 101, 164))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.NoRole, brush)
        brush = QtGui.QBrush(QtGui.QColor(52, 101, 164))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        self.menu.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Roboto")
        self.menu.setFont(font)
        self.menu.setStyleSheet("background-color: rgb(81, 176, 227);")
        self.menu.setObjectName("menu")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.menu)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.pushButton = QtWidgets.QPushButton(self.menu)
        self.pushButton.setMaximumSize(QtCore.QSize(150, 16777215))
        self.pushButton.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/incio/Imagenes/PackIconos/inicio/ic_info_outline_white.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon1)
        self.pushButton.setIconSize(QtCore.QSize(32, 32))
        self.pushButton.setAutoDefault(False)
        self.pushButton.setDefault(False)
        self.pushButton.setFlat(True)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout_11.addWidget(self.pushButton, 6, 0, 1, 1)
        self.configuracionLabel = QtWidgets.QLabel(self.menu)
        self.configuracionLabel.setEnabled(True)
        self.configuracionLabel.setMaximumSize(QtCore.QSize(60, 60))
        self.configuracionLabel.setText("")
        self.configuracionLabel.setPixmap(QtGui.QPixmap(":/configuracion/Imagenes/PackIconos/configuracion/ic_settings_white.png"))
        self.configuracionLabel.setScaledContents(True)
        self.configuracionLabel.setObjectName("configuracionLabel")
        self.gridLayout_11.addWidget(self.configuracionLabel, 2, 0, 1, 1)
        self.inicioLabel = QtWidgets.QLabel(self.menu)
        self.inicioLabel.setEnabled(True)
        self.inicioLabel.setMaximumSize(QtCore.QSize(60, 60))
        self.inicioLabel.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.inicioLabel.setAccessibleDescription("")
        self.inicioLabel.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.inicioLabel.setFrameShadow(QtWidgets.QFrame.Plain)
        self.inicioLabel.setText("")
        self.inicioLabel.setPixmap(QtGui.QPixmap(":/incio/Imagenes/PackIconos/inicio/ic_home_white.png"))
        self.inicioLabel.setScaledContents(True)
        self.inicioLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.inicioLabel.setObjectName("inicioLabel")
        self.gridLayout_11.addWidget(self.inicioLabel, 1, 0, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.menu)
        self.label_9.setMaximumSize(QtCore.QSize(60, 60))
        self.label_9.setText("")
        self.label_9.setPixmap(QtGui.QPixmap(":/ejecucion/Imagenes/PackIconos/ejecucion/ic_slow_motion_video._white.png"))
        self.label_9.setScaledContents(True)
        self.label_9.setObjectName("label_9")
        self.gridLayout_11.addWidget(self.label_9, 3, 0, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.menu)
        self.label_10.setMaximumSize(QtCore.QSize(60, 60))
        self.label_10.setText("")
        self.label_10.setPixmap(QtGui.QPixmap(":/procesamiento/Imagenes/PackIconos/procesamiento/ic_insert_photo_proc.png"))
        self.label_10.setScaledContents(True)
        self.label_10.setObjectName("label_10")
        self.gridLayout_11.addWidget(self.label_10, 4, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.menu)
        self.label_5.setMaximumSize(QtCore.QSize(60, 45))
        self.label_5.setText("")
        self.label_5.setPixmap(QtGui.QPixmap(":/Iconos/Imagenes/dron_logo_mini.png"))
        self.label_5.setScaledContents(True)
        self.label_5.setObjectName("label_5")
        self.gridLayout_11.addWidget(self.label_5, 0, 0, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.menu)
        self.label_14.setMaximumSize(QtCore.QSize(60, 60))
        self.label_14.setText("")
        self.label_14.setPixmap(QtGui.QPixmap(":/resultados/Imagenes/PackIconos/resultados/ic_art_track.png"))
        self.label_14.setScaledContents(True)
        self.label_14.setObjectName("label_14")
        self.gridLayout_11.addWidget(self.label_14, 5, 0, 1, 1)
        self.gridLayout_2.addWidget(self.menu, 0, 0, 1, 1)
        self.area1 = QtWidgets.QStackedWidget(self.centralwidget)
        self.area1.setEnabled(True)
        self.area1.setMinimumSize(QtCore.QSize(1116, 671))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(36, 111, 180))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(65, 164, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(50, 137, 217))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(18, 55, 90))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(24, 74, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(253, 252, 253))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(252, 253, 253))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(253, 252, 253))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(253, 252, 253))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.HighlightedText, brush)
        brush = QtGui.QBrush(QtGui.QColor(145, 183, 217))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.NoRole, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(36, 111, 180))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(65, 164, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(50, 137, 217))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(18, 55, 90))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(24, 74, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(253, 252, 253))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(252, 253, 253))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(253, 252, 253))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(253, 252, 253))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.HighlightedText, brush)
        brush = QtGui.QBrush(QtGui.QColor(145, 183, 217))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.NoRole, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(18, 55, 90))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(65, 164, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(50, 137, 217))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(18, 55, 90))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(24, 74, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(18, 55, 90))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(253, 252, 253))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(18, 55, 90))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(253, 252, 253))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(253, 252, 253))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(253, 252, 253))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.HighlightedText, brush)
        brush = QtGui.QBrush(QtGui.QColor(36, 111, 180))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.NoRole, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        self.area1.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Roboto")
        self.area1.setFont(font)
        self.area1.setFocusPolicy(QtCore.Qt.TabFocus)
        self.area1.setAutoFillBackground(False)
        self.area1.setStyleSheet("")
        self.area1.setObjectName("area1")
        self.area1Page1 = QtWidgets.QWidget()
        self.area1Page1.setObjectName("area1Page1")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.area1Page1)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.gridLayout_5 = QtWidgets.QGridLayout()
        self.gridLayout_5.setObjectName("gridLayout_5")
        spacerItem = QtWidgets.QSpacerItem(0, 0, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        self.gridLayout_5.addItem(spacerItem, 16, 2, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(50, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem1, 14, 0, 1, 1)
        self.PSIIcon = QtWidgets.QLabel(self.area1Page1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.PSIIcon.sizePolicy().hasHeightForWidth())
        self.PSIIcon.setSizePolicy(sizePolicy)
        self.PSIIcon.setMaximumSize(QtCore.QSize(250, 90))
        self.PSIIcon.setText("")
        self.PSIIcon.setPixmap(QtGui.QPixmap(":/psi/Imagenes/PSI.svg"))
        self.PSIIcon.setScaledContents(True)
        self.PSIIcon.setObjectName("PSIIcon")
        self.gridLayout_5.addWidget(self.PSIIcon, 14, 5, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_5.addItem(spacerItem2, 0, 3, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_5.addItem(spacerItem3, 9, 3, 1, 1)
        self.dronIcon = QtWidgets.QLabel(self.area1Page1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dronIcon.sizePolicy().hasHeightForWidth())
        self.dronIcon.setSizePolicy(sizePolicy)
        self.dronIcon.setMinimumSize(QtCore.QSize(400, 400))
        self.dronIcon.setMaximumSize(QtCore.QSize(500, 500))
        self.dronIcon.setBaseSize(QtCore.QSize(100, 100))
        self.dronIcon.setText("")
        self.dronIcon.setPixmap(QtGui.QPixmap(":/dron/Imagenes/DronLogoInicio.svg"))
        self.dronIcon.setScaledContents(True)
        self.dronIcon.setObjectName("dronIcon")
        self.gridLayout_5.addWidget(self.dronIcon, 1, 3, 4, 1)
        self.univalleIcon = QtWidgets.QLabel(self.area1Page1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.univalleIcon.sizePolicy().hasHeightForWidth())
        self.univalleIcon.setSizePolicy(sizePolicy)
        self.univalleIcon.setMaximumSize(QtCore.QSize(70, 90))
        self.univalleIcon.setText("")
        self.univalleIcon.setPixmap(QtGui.QPixmap(":/uv/Imagenes/Univalle.svg"))
        self.univalleIcon.setScaledContents(True)
        self.univalleIcon.setObjectName("univalleIcon")
        self.gridLayout_5.addWidget(self.univalleIcon, 14, 2, 1, 1)
        self.configuracionButton = QtWidgets.QPushButton(self.area1Page1)
        self.configuracionButton.setMinimumSize(QtCore.QSize(0, 50))
        self.configuracionButton.setMaximumSize(QtCore.QSize(500, 16777215))
        self.configuracionButton.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.configuracionButton.setAutoFillBackground(False)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/incio/Imagenes/PackIconos/inicio/ic_queue_play_next.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.configuracionButton.setIcon(icon2)
        self.configuracionButton.setIconSize(QtCore.QSize(32, 32))
        self.configuracionButton.setCheckable(False)
        self.configuracionButton.setAutoRepeat(False)
        self.configuracionButton.setAutoExclusive(False)
        self.configuracionButton.setFlat(True)
        self.configuracionButton.setObjectName("configuracionButton")
        self.gridLayout_5.addWidget(self.configuracionButton, 11, 3, 1, 1)
        self.gridLayout_6.addLayout(self.gridLayout_5, 0, 0, 1, 1)
        self.area1.addWidget(self.area1Page1)
        self.area1Page2 = QtWidgets.QWidget()
        self.area1Page2.setObjectName("area1Page2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.area1Page2)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.groupBox_3 = QtWidgets.QGroupBox(self.area1Page2)
        self.groupBox_3.setMinimumSize(QtCore.QSize(560, 0))
        self.groupBox_3.setMaximumSize(QtCore.QSize(560, 16777215))
        self.groupBox_3.setFlat(False)
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.conffySpinBox = QtWidgets.QDoubleSpinBox(self.groupBox_3)
        self.conffySpinBox.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.conffySpinBox.setDecimals(3)
        self.conffySpinBox.setMinimum(600.0)
        self.conffySpinBox.setMaximum(800.0)
        self.conffySpinBox.setProperty("value", 699.839)
        self.conffySpinBox.setObjectName("conffySpinBox")
        self.gridLayout_7.addWidget(self.conffySpinBox, 6, 2, 1, 1)
        self.confk2Label = QtWidgets.QLabel(self.groupBox_3)
        self.confk2Label.setMaximumSize(QtCore.QSize(70, 16777215))
        font = QtGui.QFont()
        font.setItalic(True)
        self.confk2Label.setFont(font)
        self.confk2Label.setAlignment(QtCore.Qt.AlignCenter)
        self.confk2Label.setObjectName("confk2Label")
        self.gridLayout_7.addWidget(self.confk2Label, 6, 3, 1, 1)
        self.confcyLabel = QtWidgets.QLabel(self.groupBox_3)
        self.confcyLabel.setMaximumSize(QtCore.QSize(70, 16777215))
        font = QtGui.QFont()
        font.setItalic(True)
        self.confcyLabel.setFont(font)
        self.confcyLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.confcyLabel.setObjectName("confcyLabel")
        self.gridLayout_7.addWidget(self.confcyLabel, 9, 1, 1, 1)
        self.confcxLabel = QtWidgets.QLabel(self.groupBox_3)
        self.confcxLabel.setMaximumSize(QtCore.QSize(70, 16777215))
        font = QtGui.QFont()
        font.setItalic(True)
        self.confcxLabel.setFont(font)
        self.confcxLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.confcxLabel.setObjectName("confcxLabel")
        self.gridLayout_7.addWidget(self.confcxLabel, 8, 1, 1, 1)
        self.confcvVLabel = QtWidgets.QLabel(self.groupBox_3)
        font = QtGui.QFont()
        font.setItalic(True)
        self.confcvVLabel.setFont(font)
        self.confcvVLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.confcvVLabel.setObjectName("confcvVLabel")
        self.gridLayout_7.addWidget(self.confcvVLabel, 9, 3, 1, 1)
        self.confcxSpinBox = QtWidgets.QDoubleSpinBox(self.groupBox_3)
        self.confcxSpinBox.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.confcxSpinBox.setDecimals(3)
        self.confcxSpinBox.setMinimum(300.0)
        self.confcxSpinBox.setMaximum(800.0)
        self.confcxSpinBox.setProperty("value", 675.962)
        self.confcxSpinBox.setObjectName("confcxSpinBox")
        self.gridLayout_7.addWidget(self.confcxSpinBox, 8, 2, 1, 1)
        self.confcamaraVisualizar = QtWidgets.QPushButton(self.groupBox_3)
        self.confcamaraVisualizar.setObjectName("confcamaraVisualizar")
        self.gridLayout_7.addWidget(self.confcamaraVisualizar, 13, 4, 1, 1)
        self.confcvVSpinBox = QtWidgets.QDoubleSpinBox(self.groupBox_3)
        self.confcvVSpinBox.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.confcvVSpinBox.setMinimum(10.0)
        self.confcvVSpinBox.setMaximum(360.0)
        self.confcvVSpinBox.setObjectName("confcvVSpinBox")
        self.gridLayout_7.addWidget(self.confcvVSpinBox, 9, 4, 1, 1)
        self.conffxLabel = QtWidgets.QLabel(self.groupBox_3)
        self.conffxLabel.setMaximumSize(QtCore.QSize(70, 16777215))
        font = QtGui.QFont()
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.conffxLabel.setFont(font)
        self.conffxLabel.setScaledContents(False)
        self.conffxLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.conffxLabel.setObjectName("conffxLabel")
        self.gridLayout_7.addWidget(self.conffxLabel, 4, 1, 1, 1)
        self.confcvHSpinBox = QtWidgets.QDoubleSpinBox(self.groupBox_3)
        self.confcvHSpinBox.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.confcvHSpinBox.setReadOnly(False)
        self.confcvHSpinBox.setMinimum(10.0)
        self.confcvHSpinBox.setMaximum(360.0)
        self.confcvHSpinBox.setObjectName("confcvHSpinBox")
        self.gridLayout_7.addWidget(self.confcvHSpinBox, 8, 4, 1, 1)
        self.conffxSpinBox = QtWidgets.QDoubleSpinBox(self.groupBox_3)
        self.conffxSpinBox.setEnabled(True)
        self.conffxSpinBox.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.conffxSpinBox.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.conffxSpinBox.setDecimals(3)
        self.conffxSpinBox.setMinimum(600.0)
        self.conffxSpinBox.setMaximum(800.0)
        self.conffxSpinBox.setProperty("value", 699.839)
        self.conffxSpinBox.setObjectName("conffxSpinBox")
        self.gridLayout_7.addWidget(self.conffxSpinBox, 4, 2, 1, 1)
        self.confcySpinBox = QtWidgets.QDoubleSpinBox(self.groupBox_3)
        self.confcySpinBox.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.confcySpinBox.setDecimals(3)
        self.confcySpinBox.setMinimum(200.0)
        self.confcySpinBox.setMaximum(500.0)
        self.confcySpinBox.setProperty("value", 348.013)
        self.confcySpinBox.setObjectName("confcySpinBox")
        self.gridLayout_7.addWidget(self.confcySpinBox, 9, 2, 1, 1)
        self.confk2SpinBox = QtWidgets.QDoubleSpinBox(self.groupBox_3)
        self.confk2SpinBox.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.confk2SpinBox.setDecimals(6)
        self.confk2SpinBox.setMinimum(-20.0)
        self.confk2SpinBox.setMaximum(20.0)
        self.confk2SpinBox.setProperty("value", 0.02334)
        self.confk2SpinBox.setObjectName("confk2SpinBox")
        self.gridLayout_7.addWidget(self.confk2SpinBox, 6, 4, 1, 1)
        self.confk1Label = QtWidgets.QLabel(self.groupBox_3)
        self.confk1Label.setMaximumSize(QtCore.QSize(70, 16777215))
        font = QtGui.QFont()
        font.setItalic(True)
        self.confk1Label.setFont(font)
        self.confk1Label.setAlignment(QtCore.Qt.AlignCenter)
        self.confk1Label.setObjectName("confk1Label")
        self.gridLayout_7.addWidget(self.confk1Label, 4, 3, 1, 1)
        self.confcvHLabel = QtWidgets.QLabel(self.groupBox_3)
        font = QtGui.QFont()
        font.setItalic(True)
        self.confcvHLabel.setFont(font)
        self.confcvHLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.confcvHLabel.setObjectName("confcvHLabel")
        self.gridLayout_7.addWidget(self.confcvHLabel, 8, 3, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(0, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_7.addItem(spacerItem4, 3, 3, 1, 1)
        self.confk1SpinBox = QtWidgets.QDoubleSpinBox(self.groupBox_3)
        self.confk1SpinBox.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.confk1SpinBox.setDecimals(6)
        self.confk1SpinBox.setMinimum(-20.0)
        self.confk1SpinBox.setMaximum(20.0)
        self.confk1SpinBox.setProperty("value", -0.170874)
        self.confk1SpinBox.setObjectName("confk1SpinBox")
        self.gridLayout_7.addWidget(self.confk1SpinBox, 4, 4, 1, 1)
        self.conffyLabel = QtWidgets.QLabel(self.groupBox_3)
        self.conffyLabel.setMaximumSize(QtCore.QSize(70, 16777215))
        font = QtGui.QFont()
        font.setItalic(True)
        self.conffyLabel.setFont(font)
        self.conffyLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.conffyLabel.setObjectName("conffyLabel")
        self.gridLayout_7.addWidget(self.conffyLabel, 6, 1, 1, 1)
        self.camaraIcon = QtWidgets.QLabel(self.groupBox_3)
        self.camaraIcon.setMaximumSize(QtCore.QSize(40, 40))
        self.camaraIcon.setText("")
        self.camaraIcon.setPixmap(QtGui.QPixmap(":/procesamiento/Imagenes/PackIconos/procesamiento/ic_add_a_photo.png"))
        self.camaraIcon.setScaledContents(True)
        self.camaraIcon.setObjectName("camaraIcon")
        self.gridLayout_7.addWidget(self.camaraIcon, 0, 0, 3, 1)
        self.confmodoCamararadioButton = QtWidgets.QRadioButton(self.groupBox_3)
        font = QtGui.QFont()
        font.setItalic(True)
        self.confmodoCamararadioButton.setFont(font)
        self.confmodoCamararadioButton.setObjectName("confmodoCamararadioButton")
        self.gridLayout_7.addWidget(self.confmodoCamararadioButton, 13, 2, 1, 1)
        self.confrefCamara = QtWidgets.QLineEdit(self.groupBox_3)
        self.confrefCamara.setObjectName("confrefCamara")
        self.gridLayout_7.addWidget(self.confrefCamara, 2, 3, 1, 2)
        self.confrefCamaraLabel = QtWidgets.QLabel(self.groupBox_3)
        font = QtGui.QFont()
        font.setItalic(True)
        self.confrefCamaraLabel.setFont(font)
        self.confrefCamaraLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.confrefCamaraLabel.setObjectName("confrefCamaraLabel")
        self.gridLayout_7.addWidget(self.confrefCamaraLabel, 0, 1, 3, 2)
        self.gridLayout_3.addWidget(self.groupBox_3, 2, 0, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(self.area1Page2)
        self.groupBox.setMinimumSize(QtCore.QSize(560, 0))
        self.groupBox.setMaximumSize(QtCore.QSize(560, 16777215))
        self.groupBox.setAutoFillBackground(False)
        self.groupBox.setFlat(True)
        self.groupBox.setCheckable(False)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.confdescripcion = QtWidgets.QLineEdit(self.groupBox)
        self.confdescripcion.setFrame(False)
        self.confdescripcion.setObjectName("confdescripcion")
        self.gridLayout_4.addWidget(self.confdescripcion, 9, 1, 1, 2)
        self.confnombreUsuario = QtWidgets.QLineEdit(self.groupBox)
        self.confnombreUsuario.setStyleSheet("")
        self.confnombreUsuario.setText("")
        self.confnombreUsuario.setFrame(False)
        self.confnombreUsuario.setClearButtonEnabled(True)
        self.confnombreUsuario.setObjectName("confnombreUsuario")
        self.gridLayout_4.addWidget(self.confnombreUsuario, 5, 1, 1, 2)
        self.confnombreMision = QtWidgets.QLineEdit(self.groupBox)
        self.confnombreMision.setStyleSheet("")
        self.confnombreMision.setInputMask("")
        self.confnombreMision.setText("")
        self.confnombreMision.setFrame(False)
        self.confnombreMision.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.confnombreMision.setDragEnabled(False)
        self.confnombreMision.setReadOnly(False)
        self.confnombreMision.setCursorMoveStyle(QtCore.Qt.LogicalMoveStyle)
        self.confnombreMision.setClearButtonEnabled(True)
        self.confnombreMision.setObjectName("confnombreMision")
        self.gridLayout_4.addWidget(self.confnombreMision, 3, 1, 1, 2)
        self.confcomboMunicipio = QtWidgets.QComboBox(self.groupBox)
        self.confcomboMunicipio.setFrame(False)
        self.confcomboMunicipio.setObjectName("confcomboMunicipio")
        self.confcomboMunicipio.addItem("")
        self.gridLayout_4.addWidget(self.confcomboMunicipio, 2, 1, 1, 2)
        self.confnombreFachada = QtWidgets.QLineEdit(self.groupBox)
        self.confnombreFachada.setStyleSheet("")
        self.confnombreFachada.setText("")
        self.confnombreFachada.setFrame(False)
        self.confnombreFachada.setClearButtonEnabled(True)
        self.confnombreFachada.setObjectName("confnombreFachada")
        self.gridLayout_4.addWidget(self.confnombreFachada, 8, 1, 1, 2)
        self.confcomboDepartamento = QtWidgets.QComboBox(self.groupBox)
        palette = QtGui.QPalette()
        self.confcomboDepartamento.setPalette(palette)
        self.confcomboDepartamento.setAcceptDrops(False)
        self.confcomboDepartamento.setFrame(True)
        self.confcomboDepartamento.setModelColumn(0)
        self.confcomboDepartamento.setObjectName("confcomboDepartamento")
        self.confcomboDepartamento.addItem("")
        self.gridLayout_4.addWidget(self.confcomboDepartamento, 1, 1, 1, 2)
        self.confcorreoUsuario = QtWidgets.QLineEdit(self.groupBox)
        self.confcorreoUsuario.setFrame(False)
        self.confcorreoUsuario.setClearButtonEnabled(True)
        self.confcorreoUsuario.setObjectName("confcorreoUsuario")
        self.gridLayout_4.addWidget(self.confcorreoUsuario, 6, 1, 1, 2)
        self.infoIcon = QtWidgets.QLabel(self.groupBox)
        self.infoIcon.setMaximumSize(QtCore.QSize(40, 40))
        self.infoIcon.setText("")
        self.infoIcon.setPixmap(QtGui.QPixmap(":/configuracion/Imagenes/PackIconos/configuracion/ic_perm_contact_calendar.png"))
        self.infoIcon.setScaledContents(True)
        self.infoIcon.setObjectName("infoIcon")
        self.gridLayout_4.addWidget(self.infoIcon, 0, 0, 3, 1)
        self.gridLayout_3.addWidget(self.groupBox, 1, 0, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem5, 9, 14, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.area1Page2)
        self.label_6.setMinimumSize(QtCore.QSize(35, 45))
        self.label_6.setMaximumSize(QtCore.QSize(35, 45))
        self.label_6.setText("")
        self.label_6.setPixmap(QtGui.QPixmap(":/uv/Imagenes/Univalle.svg"))
        self.label_6.setScaledContents(True)
        self.label_6.setObjectName("label_6")
        self.gridLayout_3.addWidget(self.label_6, 9, 13, 1, 1)
        self.label = QtWidgets.QLabel(self.area1Page2)
        self.label.setMaximumSize(QtCore.QSize(100, 45))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(":/psi/Imagenes/PSI.svg"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.gridLayout_3.addWidget(self.label, 9, 15, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem6, 9, 16, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.area1Page2)
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_7.setObjectName("label_7")
        self.gridLayout_3.addWidget(self.label_7, 0, 0, 1, 1)
        self.groupBox_5 = QtWidgets.QGroupBox(self.area1Page2)
        self.groupBox_5.setMinimumSize(QtCore.QSize(560, 0))
        self.groupBox_5.setMaximumSize(QtCore.QSize(560, 16777215))
        self.groupBox_5.setObjectName("groupBox_5")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.groupBox_5)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.locIcon = QtWidgets.QLabel(self.groupBox_5)
        self.locIcon.setMaximumSize(QtCore.QSize(40, 40))
        self.locIcon.setText("")
        self.locIcon.setPixmap(QtGui.QPixmap(":/configuracion/Imagenes/PackIconos/configuracion/ic_add_location.png"))
        self.locIcon.setScaledContents(True)
        self.locIcon.setObjectName("locIcon")
        self.gridLayout_9.addWidget(self.locIcon, 0, 0, 1, 1)
        self.confimportarWaypoints = QtWidgets.QPushButton(self.groupBox_5)
        self.confimportarWaypoints.setObjectName("confimportarWaypoints")
        self.gridLayout_9.addWidget(self.confimportarWaypoints, 0, 1, 1, 1)
        self.confrutaIcon = QtWidgets.QLabel(self.groupBox_5)
        self.confrutaIcon.setObjectName("confrutaIcon")
        self.gridLayout_9.addWidget(self.confrutaIcon, 1, 0, 1, 1)
        self.confrutaWaypoints = QtWidgets.QLineEdit(self.groupBox_5)
        self.confrutaWaypoints.setObjectName("confrutaWaypoints")
        self.gridLayout_9.addWidget(self.confrutaWaypoints, 1, 1, 1, 1)
        self.gridLayout_3.addWidget(self.groupBox_5, 9, 0, 1, 1)
        self.groupBox_2 = QtWidgets.QGroupBox(self.area1Page2)
        self.groupBox_2.setMinimumSize(QtCore.QSize(560, 0))
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.confplot = PlotWidget(self.groupBox_2)
        self.confplot.setMinimumSize(QtCore.QSize(470, 480))
        self.confplot.setStyleSheet("")
        self.confplot.setObjectName("confplot")
        self.gridLayout_10.addWidget(self.confplot, 1, 1, 1, 2)
        self.label_4 = QtWidgets.QLabel(self.groupBox_2)
        self.label_4.setMinimumSize(QtCore.QSize(20, 20))
        self.label_4.setMaximumSize(QtCore.QSize(20, 20))
        self.label_4.setStyleSheet("background-color: rgb(52, 101, 164);")
        self.label_4.setText("")
        self.label_4.setObjectName("label_4")
        self.gridLayout_10.addWidget(self.label_4, 2, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.groupBox_2)
        self.label_3.setObjectName("label_3")
        self.gridLayout_10.addWidget(self.label_3, 2, 2, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.groupBox_2)
        self.label_2.setObjectName("label_2")
        self.gridLayout_10.addWidget(self.label_2, 2, 1, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.groupBox_2)
        self.label_8.setMinimumSize(QtCore.QSize(40, 40))
        self.label_8.setMaximumSize(QtCore.QSize(40, 40))
        self.label_8.setText("")
        self.label_8.setPixmap(QtGui.QPixmap(":/configuracion/Imagenes/PackIconos/configuracion/ic_map.png"))
        self.label_8.setScaledContents(True)
        self.label_8.setObjectName("label_8")
        self.gridLayout_10.addWidget(self.label_8, 0, 0, 1, 1)
        self.gridLayout_3.addWidget(self.groupBox_2, 1, 11, 4, 6)
        self.ejecucionButton = QtWidgets.QPushButton(self.area1Page2)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/ejecucion/Imagenes/PackIconos/ejecucion/ic_slow_motion_video.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.ejecucionButton.setIcon(icon3)
        self.ejecucionButton.setIconSize(QtCore.QSize(32, 32))
        self.ejecucionButton.setObjectName("ejecucionButton")
        self.gridLayout_3.addWidget(self.ejecucionButton, 9, 11, 1, 1)
        self.area1.addWidget(self.area1Page2)
        self.area1Page3 = QtWidgets.QWidget()
        self.area1Page3.setObjectName("area1Page3")
        self.treeWidget = QtWidgets.QTreeWidget(self.area1Page3)
        self.treeWidget.setGeometry(QtCore.QRect(320, 270, 256, 192))
        self.treeWidget.setObjectName("treeWidget")
        self.treeWidget.headerItem().setText(0, "1")
        self.procesamientoButton = QtWidgets.QPushButton(self.area1Page3)
        self.procesamientoButton.setGeometry(QtCore.QRect(380, 610, 296, 27))
        self.procesamientoButton.setObjectName("procesamientoButton")
        self.label_11 = QtWidgets.QLabel(self.area1Page3)
        self.label_11.setGeometry(QtCore.QRect(5, 5, 560, 29))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_11.setObjectName("label_11")
        self.area1.addWidget(self.area1Page3)
        self.area1Page4 = QtWidgets.QWidget()
        self.area1Page4.setObjectName("area1Page4")
        self.tableWidget = QtWidgets.QTableWidget(self.area1Page4)
        self.tableWidget.setGeometry(QtCore.QRect(240, 455, 256, 192))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.resultadosButton = QtWidgets.QPushButton(self.area1Page4)
        self.resultadosButton.setGeometry(QtCore.QRect(523, 515, 231, 27))
        self.resultadosButton.setObjectName("resultadosButton")
        self.label_12 = QtWidgets.QLabel(self.area1Page4)
        self.label_12.setGeometry(QtCore.QRect(0, 0, 560, 29))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_12.setFont(font)
        self.label_12.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_12.setObjectName("label_12")
        self.area1.addWidget(self.area1Page4)
        self.area1Page5 = QtWidgets.QWidget()
        self.area1Page5.setObjectName("area1Page5")
        self.inicioButton = QtWidgets.QPushButton(self.area1Page5)
        self.inicioButton.setGeometry(QtCore.QRect(465, 490, 94, 27))
        self.inicioButton.setObjectName("inicioButton")
        self.label_13 = QtWidgets.QLabel(self.area1Page5)
        self.label_13.setGeometry(QtCore.QRect(0, 0, 560, 29))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_13.setFont(font)
        self.label_13.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_13.setObjectName("label_13")
        self.area1.addWidget(self.area1Page5)
        self.gridLayout_2.addWidget(self.area1, 0, 1, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_2, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)

        self.retranslateUi(MainWindow)
        self.area1.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.configuracionButton.setText(_translate("MainWindow", "Nueva Misión"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Parametros de la cámara"))
        self.confk2Label.setText(_translate("MainWindow", "k2"))
        self.confcyLabel.setText(_translate("MainWindow", "cy"))
        self.confcxLabel.setText(_translate("MainWindow", "cx"))
        self.confcvVLabel.setText(_translate("MainWindow", "cv (V)"))
        self.confcamaraVisualizar.setText(_translate("MainWindow", "Visualizar"))
        self.confcvVSpinBox.setSuffix(_translate("MainWindow", "°"))
        self.conffxLabel.setText(_translate("MainWindow", "fx"))
        self.confcvHSpinBox.setSuffix(_translate("MainWindow", "°"))
        self.confk1Label.setText(_translate("MainWindow", "k1"))
        self.confcvHLabel.setText(_translate("MainWindow", "cv (H)"))
        self.conffyLabel.setText(_translate("MainWindow", "fy"))
        self.confmodoCamararadioButton.setText(_translate("MainWindow", "Modo manual"))
        self.confrefCamaraLabel.setText(_translate("MainWindow", "Referecia de la cámara"))
        self.groupBox.setTitle(_translate("MainWindow", "Datos de la mision"))
        self.confdescripcion.setPlaceholderText(_translate("MainWindow", "Descripción"))
        self.confnombreUsuario.setPlaceholderText(_translate("MainWindow", "Nombre de usuario"))
        self.confnombreMision.setPlaceholderText(_translate("MainWindow", "Nombre de la misión"))
        self.confcomboMunicipio.setItemText(0, _translate("MainWindow", "Municipio"))
        self.confnombreFachada.setPlaceholderText(_translate("MainWindow", "Nombre de la fachada"))
        self.confcomboDepartamento.setItemText(0, _translate("MainWindow", "Departamento"))
        self.confcorreoUsuario.setPlaceholderText(_translate("MainWindow", "Correo electrónico del  usuario"))
        self.label_7.setText(_translate("MainWindow", "CONFIGURACIÓN"))
        self.groupBox_5.setTitle(_translate("MainWindow", "Importar waypoints"))
        self.confimportarWaypoints.setText(_translate("MainWindow", "Importar"))
        self.confrutaIcon.setText(_translate("MainWindow", "Ruta/"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Datos de la trayectoria"))
        self.label_3.setText(_translate("MainWindow", "TextLabel"))
        self.label_2.setText(_translate("MainWindow", "Puntos de trayectoria"))
        self.ejecucionButton.setText(_translate("MainWindow", "Iniciar misión"))
        self.procesamientoButton.setText(_translate("MainWindow", "Iniciar Procesamiento"))
        self.label_11.setText(_translate("MainWindow", "EJECUCIÓN"))
        self.resultadosButton.setText(_translate("MainWindow", "Anlizar Resultados"))
        self.label_12.setText(_translate("MainWindow", "PROCESAMIENTO"))
        self.inicioButton.setText(_translate("MainWindow", "Finalizar"))
        self.label_13.setText(_translate("MainWindow", "RESULTADOS"))

from pyqtgraph import PlotWidget
import imagenes_rc
